pipeline {
    agent {
        docker {
            image 'ubuntu:22.04'
            args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        REGISTRY = "localhost:5001"
    }

    stages {

        stage('Install Dependencies & Terraform') {
            steps {
                sh '''
                    echo "📌 Updating & Installing Tools..."
                    apt-get update -y
                    apt-get install -y curl unzip docker.io git

                    echo "⬇️ Installing Terraform..."
                    curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
                    unzip -o terraform.zip
                    mv terraform /usr/local/bin/
                    chmod +x /usr/local/bin/terraform
                    terraform -version
                '''
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-token',
                    url: 'https://github.com/fayizsaleem/devops-platform.git'
            }
        }

        stage('Build User Service') {
            steps {
                dir('services/user-service') {
                    sh 'docker build -t user-service:local .'
                }
            }
        }

        stage('Build Order Service') {
            steps {
                dir('services/order-service') {
                    sh 'docker build -t order-service:local .'
                }
            }
        }

        stage('Push to Local Registry') {
            steps {
                sh '''
                    echo "📦 Pushing Images to Local Registry..."
                    docker tag user-service:local $REGISTRY/user-service:latest
                    docker push $REGISTRY/user-service:latest

                    docker tag order-service:local $REGISTRY/order-service:latest
                    docker push $REGISTRY/order-service:latest
                '''
            }
        }

        stage('Deploy Infrastructure') {
            steps {
                dir('terraform') {
                    sh '''
                        echo "🚀 Deploying Terraform Infra..."
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }
    }
}
