pipeline {
    agent any

    environment {
        REGISTRY = "localhost:5001"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/fayizsaleem/devops-platform.git', credentialsId: 'github-token'
            }
        }

        stage('Install Terraform') {
            steps {
                sh '''
                    apk add --update curl bash git unzip
                    rm -rf terraform terraform.zip
                    curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
                    unzip -o terraform.zip
                    mv terraform /usr/local/bin/
                    chmod +x /usr/local/bin/terraform
                    terraform -version
                '''
            }
        }

        stage('Build User Service') {
            steps {
                dir('services/user-service') {
                    sh 'docker build -t user-service:local .'
                }
            }
        }

        stage('Build Order Service') {
            steps {
                dir('services/order-service') {
                    sh 'docker build -t order-service:local .'
                    // ignore npm test for now
                    sh 'echo "Skipping tests for now 🚫 npm test"'
                }
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                    docker tag user-service:local $REGISTRY/user-service:latest
                    docker tag order-service:local $REGISTRY/order-service:latest
                    docker push $REGISTRY/user-service:latest
                    docker push $REGISTRY/order-service:latest
                '''
            }
        }

        stage('Deploy Infra') {
            steps {
                sh '''
                    echo "🔍 Checking Terraform Folder"
                    if [ ! -d "$WORKSPACE/terraform" ]; then
                        unzip -o $WORKSPACE/terraform.zip -d $WORKSPACE/terraform
                    fi

                    echo "🚀 Running Terraform"
                    cd $WORKSPACE/terraform
                    terraform init
                    terraform apply -auto-approve
                '''
            }
        }
    }
}

