pipeline {

    agent {
        docker {
            image 'docker:24.0.5-cli'
            args '--privileged -u root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=""'
        }
    }

    environment {
        REGISTRY = "localhost:5001"
        USER_IMAGE = "${REGISTRY}/user-service:latest"
        ORDER_IMAGE = "${REGISTRY}/order-service:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'github-token',
                url: 'https://github.com/fayizsaleem/devops-platform.git'
            }
        }

        stage('Install Terraform') {
            steps {
                sh '''
                    apk add --update curl bash git unzip
                    curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
                    unzip -o terraform.zip
                    mv terraform /usr/local/bin/
                    chmod +x /usr/local/bin/terraform
                    terraform -version
                '''
            }
        }

        stage('Build User Service') {
            steps {
                dir('services/user-service') {
                    sh 'docker build -t user-service:local .'
                }
            }
        }

        stage('Build Order Service') {
            steps {
                dir('services/order-service') {
                    sh 'docker build -t order-service:local .'
                    sh 'npm test || true'
                }
            }
        }

        stage('Push Images') {
            steps {
                sh '''
                    docker tag user-service:local $USER_IMAGE
                    docker push $USER_IMAGE
                    
                    docker tag order-service:local $ORDER_IMAGE
                    docker push $ORDER_IMAGE
                '''
            }
        }

        stage('Deploy Infra') {
            steps {
                dir('terraform') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }
    }
}
